name: Test workflow on running load testing
on:
  push:
    branches: 
      - loadtest_script_setup

jobs:
  run-loadtest:
    name: Run load testing and save logs
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Install WRK
        run: |
          sudo apt-get update -y
          sudo apt-get install -y build-essential libssl-dev git unzip 
          git clone https://github.com/wg/wrk.git wrk
          cd wrk
          sudo make
          sudo cp wrk /usr/local/bin
          cd ..
          sudo rm -rf wrk

      - name: Run load testing
        run: |
          cd loadtest
          ./loadtest_script.sh 200 4

      - name: Commit logs
        run: |
          git config --global user.name 'AutoCommitBot'
          git config --global user.email 'bot@email.com'
          git add .
          git commit -m "Commit load testing logs"
          git push origin loadtest_script_setup
